set dotenv-filename := ".libdragon-sys-env"

default:
    @echo Nothing to do

build-release: 
    cargo build --release
    @just finish-rom

build-release-verbose: 
    cargo build --release --verbose
    @just finish-rom

finish-rom:
    @if [ -d filesystem ]; then  \
        "$DEP_LIBDRAGON_SYS_N64_TOOLDIR"/mkdfs "$ELF_FILE.dfs" filesystem >/dev/null; \
    fi                           

    @"$DEP_LIBDRAGON_SYS_N64_TOOLDIR"/n64sym "$ELF_FILE" "$ELF_FILE.sym"
    @cp "$ELF_FILE" "$ELF_FILE.stripped"
    @"$DEP_LIBDRAGON_SYS_TOOLCHAIN_BIN"strip "$ELF_FILE.stripped"

    @if [ -f "$ELF_FILE.dfs" ]; then \
        "$DEP_LIBDRAGON_SYS_N64_TOOLDIR"/n64tool -t "GAME" \
            --toc -o "$ELF_FILE.z64" --align 256 "$ELF_FILE.stripped" --align 8 "$ELF_FILE.sym" --align 16 "$ELF_FILE.dfs"; \
    else \
        "$DEP_LIBDRAGON_SYS_N64_TOOLDIR"/n64tool -t "GAME" \
            --toc -o "$ELF_FILE.z64" --align 256 "$ELF_FILE.stripped" --align 8 "$ELF_FILE.sym" --align 8; \
    fi

    @echo "ROM is in $ELF_FILE.z64"

